### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [alsedi/AnimatedSwitch#1]
<img width="626" alt="screen shot 2016-04-27 at 3 13 04 pm" src="https://cloud.githubusercontent.com/assets/6511079/14869776/964ceebe-0c8a-11e6-9065-73ea563d4647.png">
Should be something like:

> UISwitch which paints over the parent view with the color in Swift 🔶

**Comment by alsedi** [comment]
Good point, thanks.
